// This file was generated by Examples/Cpp/generate_main.py

#include "ximu3_ros/UdpConnection_ros.h"
#include "ros/ros.h"
int main(int argc, char** argv)
{
        ros::init(argc, argv, "talker");
	UdpConnection();
}
